### ISSUE TITLE
Tracking: firmware doc updates

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_Radios#23]
- [ ] Youtube video demonstration
- [x] Put Device flashing instructions in front of Host code [1) flip to reset 2) flash pass through 3) flip to normal 4) flash device 5) flip to reset 6) flash host]
- [x] Make the radio flashing non volatile memory better
- [x] Insert line about how you cannot brick your radios 
- [x] Remove, or rather improve, the line about how if you have blue buttons you don't need a capacitor because that has nothing to do with the Dongle
- [x] Can we not use a newer version of Arduino IDE
- [x] Add line about how it does not matter if you pick `.cu` or `.tty`
- [x] Add clarity about channel number selection, talk about how both Host and Device need to be on the same channel
- [x] Update README.md to direct to the openbci docs page for installation instructions. 
- [x] Specify "Test Builds 2015-10-18" chipKIT core version.

**Comment by andrewjaykeller** [comment]
@conorrussomanno is a youtube video planned to be made while your sister is in town? If not please add it! Would be super enabling for people to update!
